### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by fortegas** [dreed47/WifiMQTTManager#12]
I have been using your library but my mqtt server needs user/password to be used. I have try with user:password@host in the configuration of the host without success. Is there any other manner to use your library with mqtt server with security enabled?. Thank you.

**Comment by dreed47** [comment]
For the use of this library it assumes you have already setup your MQTT server for use with Node Red.  You put your MQTT user/password info in the Node Red configuration panel for the MQTT server.  See https://cookbook.nodered.org/mqtt/connect-to-broker
